server:
  port: 9050


spring:
  application:
    name: account-service
  main:
    allow-bean-definition-overriding: true
  datasource:
    initialize: false
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  cassandra:
    keyspace-name: springcloud
    schema-action: CREATE_IF_NOT_EXISTS
    contact-points: localhost
    local-datacenter: datacenter1
    port: 9042
    username: cassandra
    password: cassandra

management:
  tracing:
    sampling:
      probability: 1
    enabled: true
    propagation:
      type: b3
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9058/eureka/
