server:
  port: 9052


spring:
  application:
    name: notification-service

  autoconfigure:
    exclude:
      - org.springframework.boot.actuate.autoconfigure.tracing.zipkin.ZipkinAutoConfiguration

  rabbitmq:
    username: reversetech
    password: reversetech

  cloud:
    function:
      definition: onNotification
    stream:
      bindings:
        onNotification-in-0:
          destination: msqueue
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9058/eureka/

management:
  tracing:
    sampling:
      probability: 1.0  # Tüm istekleri Zipkin'e logla (Production'da 0.1 gibi olabilir)