server:
  port: 9051


spring:
  application:
    name: ticket-service
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
    - org.springframework.cloud.function.context.config.ContextFunctionCatalogAutoConfiguration
    - org.springframework.boot.actuate.autoconfigure.tracing.zipkin.ZipkinAutoConfiguration

  datasource:
    url: jdbc:postgresql://localhost:5432/cloud
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    initialize: false
    hikari:
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    enabled: true
    autoconfigure:
      exclude: org.springframework.boot.autoconfigure.transaction.TransactionManagerCustomizationAutoConfiguration
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    username: reversetech
    password: reversetech

  cloud:
    function:
      definition: sendToQueue
    stream:
      bindings:
        sendToQueue-in-0:
          destination: msqueue
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9058/eureka/

management:
  tracing:
    sampling:
      probability: 1.0