version: 3;
services:
  cassandra:
    image: cassandra
    ports:
      - 9042:9042

  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: microservice-app

  elasticsearch:
    image: elasticsearch:8.12.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: single-node
